name: Create Major Release

on:
  workflow_dispatch:

env:
  # Set the token for the checkout action
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ env.GITHUB_TOKEN }}

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Bump version
        run: |
          git config --global user.email "github-actions@numerator.io"
          git config --global user.name "Github Actions"
          ./tools/create_release.sh major
