name: Release Workflow

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (e.g., 1.0.0)'
        required: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if release version exists
        uses: actions/github-script@v5
        with:
          script: |
            const version = "${{ github.event.inputs.release_version }}"
            const octokit = github.getOctokit("${{ secrets.GITHUB_TOKEN }}");
            const { data: releases } = await octokit.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const releaseExists = releases.some(release => release.tag_name === version);
            if (!releaseExists) {
              core.setFailed(`Release version ${version} does not exist.`);
            }
