name: Analyze Pull Request

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}      
  cancel-in-progress: true

jobs:
  linting:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install dependencies
      run: CI=true yarn install

    - name: Run lint
      run: yarn lint && yarn check --integrity

    - name: Run build
      run: yarn build

    - name: Run test
      run: yarn test
